# Generated by Django 4.1.6 on 2023-04-10 10:26

import cloudapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_caption',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=None, upload_to=cloudapp.models.user_directory_path),
            preserve_default=False,
        ),
    ]
